/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new account */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email and password */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["UsersController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user profile */
        patch: operations["UsersController_updateProfile"];
        trace?: never;
    };
    "/api/v1/users/me/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List emergency contacts */
        get: operations["UsersController_listContacts"];
        put?: never;
        /** Add emergency contact */
        post: operations["UsersController_addContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/contacts/{contactId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete emergency contact */
        delete: operations["UsersController_deleteContact"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hazards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get active hazards in area */
        get: operations["HazardsController_findNearby"];
        put?: never;
        /** Report a hazard */
        post: operations["HazardsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hazards/{hazardId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm a hazard is still present */
        post: operations["HazardsController_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hazards/{hazardId}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report hazard is no longer present */
        post: operations["HazardsController_dismiss"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hazards/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get hazards along a route */
        post: operations["HazardsController_findAlongRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sensor/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload batched accelerometer readings
         * @description Upload a batch of sensor readings collected during a ride. Readings are processed server-side to update road quality scores.
         */
        post: operations["SensorController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roads/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get road segments near a location */
        get: operations["RoadsController_findNearby"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roads/fun-zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get fun zones in a bounding box */
        get: operations["RoadsController_findFunZones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roads/{segmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get road segment details (Road Preview Card data) */
        get: operations["RoadsController_findById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rides/{rideId}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Share or update sharing for a ride */
        post: operations["SharingController_toggleShare"];
        /** Remove sharing for a ride */
        delete: operations["SharingController_unshare"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rides/shared/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View a shared ride by token (no auth required) */
        get: operations["SharingController_getSharedRide"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rides/community": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse community rides nearby */
        get: operations["SharingController_listCommunityRides"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user's rides */
        get: operations["RidesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rides/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a new ride */
        post: operations["RidesController_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rides/{rideId}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop an active ride */
        post: operations["RidesController_stop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rides/{rideId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ride details with stats */
        get: operations["RidesController_getDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rides/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import a GPX file as a route */
        post: operations["RidesController_importGpx"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rides/{rideId}/gpx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export ride as GPX */
        get: operations["RidesController_exportGpx"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/safety/crash-alert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send crash alert to emergency contacts
         * @description Triggered by the app when crash detection activates and the countdown timer expires without cancellation.
         */
        post: operations["SafetyController_sendCrashAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roads/tiles/{z}/{x}/{y}.mvt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get vector map tile with road quality overlay */
        get: operations["TilesController_getTile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weather/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current weather at a location */
        get: operations["WeatherController_getCurrent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weather/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get weather conditions along a route
         * @description Samples weather every ~20km along the route and returns conditions at each point plus alerts for dangerous conditions (rain, ice, storms, wind).
         */
        post: operations["WeatherController_getRouteWeather"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commute/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user's saved commute routes */
        get: operations["CommuteController_listRoutes"];
        put?: never;
        /** Save a commute route */
        post: operations["CommuteController_createRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commute/routes/{routeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a commute route */
        delete: operations["CommuteController_deleteRoute"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commute/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current commute status (hazards, weather, route quality) */
        get: operations["CommuteController_getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commute/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get commute statistics */
        get: operations["CommuteController_getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roads/{segmentId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get reviews for a road segment */
        get: operations["ReviewsController_list"];
        /** Update your review for a road segment */
        put: operations["ReviewsController_update"];
        /** Submit a road review */
        post: operations["ReviewsController_create"];
        /** Delete your review for a road segment */
        delete: operations["ReviewsController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Follow a user */
        post: operations["FollowersController_follow"];
        /** Unfollow a user */
        delete: operations["FollowersController_unfollow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a user's followers */
        get: operations["FollowersController_listFollowers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List who a user is following */
        get: operations["FollowersController_listFollowing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed/rides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ride feed from followed riders */
        get: operations["FollowersController_getFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example rider@example.com */
            email: string;
            /** @example securePassword123 */
            password: string;
            /** @example Martin_CZ */
            display_name: string;
        };
        UserResponse: {
            id: string;
            email: string;
            display_name: string;
            phone?: string | null;
            created_at: string;
        };
        AuthResponseDto: {
            access_token: string;
            refresh_token: string;
            /** @description Seconds until access token expires */
            expires_in: number;
            user: components["schemas"]["UserResponse"];
        };
        LoginDto: {
            /** @example rider@example.com */
            email: string;
            password: string;
        };
        RefreshTokenDto: {
            refresh_token: string;
        };
        LatLngResponse: {
            lat: number;
            lng: number;
        };
        UserResponseDto: {
            id: string;
            email: string;
            display_name: string;
            phone: string | null;
            home_location: components["schemas"]["LatLngResponse"] | null;
            work_location: components["schemas"]["LatLngResponse"] | null;
            preferences: Record<string, never>;
            created_at: string;
        };
        LatLngDto: {
            lat: number;
            lng: number;
        };
        UserPreferencesDto: {
            units?: string;
            daily_km?: number;
            min_quality?: number;
            road_types?: string[];
            record_gps?: boolean;
            crash_detection?: boolean;
        };
        UpdateProfileDto: {
            display_name?: string;
            phone?: string;
            home_location?: components["schemas"]["LatLngDto"];
            work_location?: components["schemas"]["LatLngDto"];
            preferences?: components["schemas"]["UserPreferencesDto"];
        };
        ContactResponseDto: {
            id: string;
            name: string;
            phone: string;
            is_emergency: boolean;
            created_at: string;
        };
        CreateContactDto: {
            /** @example Jane Doe */
            name: string;
            /** @example +420123456789 */
            phone: string;
            /** @default true */
            is_emergency: boolean;
        };
        HazardResponseDto: {
            id: string;
            lat: number;
            lng: number;
            hazard_type: string;
            severity: string;
            note: string | null;
            confirmations: number;
            reporter: string | null;
            road_name: string | null;
            created_at: string;
            expires_at: string;
        };
        CreateHazardDto: {
            /** @example 49.1 */
            lat: number;
            /** @example 16.75 */
            lng: number;
            /**
             * @example pothole
             * @enum {string}
             */
            hazard_type: "pothole" | "gravel" | "oil_spill" | "roadworks" | "animals" | "police" | "flooding" | "ice" | "other";
            /**
             * @default medium
             * @enum {string}
             */
            severity: "low" | "medium" | "high";
            note?: string;
        };
        LatLng: {
            lat: number;
            lng: number;
        };
        RouteHazardsDto: {
            route: components["schemas"]["LatLng"][];
            /** @default 200 */
            buffer_m: number;
        };
        SensorReadingDto: {
            /** @description Unix timestamp milliseconds */
            t: number;
            /** @description Accelerometer X (m/s²) */
            ax: number;
            /** @description Accelerometer Y (m/s²) */
            ay: number;
            /** @description Accelerometer Z (m/s²) */
            az: number;
            lat?: number;
            lng?: number;
            /** @description Speed in m/s */
            speed?: number;
        };
        UploadSensorDataDto: {
            /** Format: uuid */
            ride_id: string;
            /** @example iPhone 15 Pro */
            device_model?: string;
            readings: components["schemas"]["SensorReadingDto"][];
        };
        UploadResponseDto: {
            /** @description Number of readings accepted */
            accepted: number;
            /** @description Road segments that got new quality data */
            segments_updated: number;
        };
        RoadSegmentDto: {
            id: string;
            road_name: string | null;
            road_number: string | null;
            /** @description 1-5 scale */
            quality_score: number | null;
            /** @description 0-5 scale */
            curviness_score: number;
            surface_type: string;
            length_m: number;
            /** @description 0-100, based on number of readings */
            confidence: number;
            reading_count: number;
            last_updated: string;
            /** @description Distance from query point in meters */
            distance_m?: number;
        };
        FunZoneDto: {
            id: string;
            name: string | null;
            composite_score: number;
            road_count: number;
            total_curve_km: number | null;
            avg_quality: number | null;
            best_season: string | null;
            boundary: Record<string, never>[];
        };
        QualityBreakdownDto: {
            excellent: number;
            good: number;
            fair: number;
            poor: number;
            very_poor: number;
        };
        RoadSegmentDetailDto: {
            id: string;
            road_name: string | null;
            road_number: string | null;
            /** @description 1-5 scale */
            quality_score: number | null;
            /** @description 0-5 scale */
            curviness_score: number;
            surface_type: string;
            length_m: number;
            /** @description 0-100, based on number of readings */
            confidence: number;
            reading_count: number;
            last_updated: string;
            /** @description Distance from query point in meters */
            distance_m?: number;
            geometry: Record<string, never>[];
            elevation_min: number | null;
            elevation_max: number | null;
            quality_breakdown: components["schemas"]["QualityBreakdownDto"];
            active_hazards: number;
            review_count: number;
            avg_review_rating: number | null;
            riders_per_month: number;
        };
        ToggleShareDto: {
            /** @description Whether the ride should be publicly visible */
            is_public: boolean;
        };
        SharedRideResponseDto: {
            share_token: string;
            is_public: boolean;
            share_url: string;
        };
        SharedRideDetailDto: {
            id: string;
            rider_name: string;
            ride_type: string;
            started_at: string;
            ended_at: string | null;
            distance_km: number | null;
            avg_speed: number | null;
            max_speed: number | null;
            avg_road_quality: number | null;
            duration_min: number | null;
            route_geometry: Record<string, never>[] | null;
        };
        CommunityRideDto: {
            id: string;
            share_token: string;
            rider_name: string;
            ride_type: string;
            started_at: string;
            distance_km: number | null;
            avg_speed: number | null;
            avg_road_quality: number | null;
            duration_min: number | null;
        };
        RideSummaryDto: {
            id: string;
            status: string;
            ride_type: string;
            started_at: string;
            ended_at: string | null;
            distance_km: number | null;
            avg_speed: number | null;
            avg_road_quality: number | null;
            duration_min: number | null;
        };
        RideListResponseDto: {
            rides: components["schemas"]["RideSummaryDto"][];
            total: number;
        };
        StartRideDto: {
            /**
             * @default free
             * @enum {string}
             */
            ride_type: "free" | "commute" | "trip" | "tracked";
        };
        RideResponseDto: {
            id: string;
            status: string;
            ride_type: string;
            started_at: string;
            ended_at: string | null;
            distance_km: number | null;
            avg_speed: number | null;
            avg_road_quality: number | null;
        };
        RideDetailDto: {
            id: string;
            status: string;
            ride_type: string;
            started_at: string;
            ended_at: string | null;
            distance_km: number | null;
            avg_speed: number | null;
            avg_road_quality: number | null;
            duration_min: number | null;
            max_speed: number | null;
            route_geometry: Record<string, never>[] | null;
            elevation_gain: number | null;
            elevation_loss: number | null;
            curve_count: number | null;
            max_lean_angle: number | null;
            fuel_estimate_l: number | null;
            segments: Record<string, never>[];
        };
        CrashAlertDto: {
            /** @example 49.1 */
            lat: number;
            /** @example 16.75 */
            lng: number;
            /** Format: uuid */
            ride_id?: string;
            /** @description Last known speed in km/h */
            speed_at_impact?: number;
        };
        CrashAlertResponseDto: {
            contacts_notified: number;
            alert_id: string;
        };
        WeatherResponseDto: {
            temperature_c: number;
            /** @enum {string} */
            condition: "clear" | "cloudy" | "rain" | "storm" | "snow" | "fog" | "ice";
            wind_kmh: number;
            precipitation_chance: number;
            /** @enum {string} */
            road_condition: "dry" | "wet" | "icy" | "unknown";
            /** @example 14°C · Dry roads · Wind 12 km/h */
            description: string;
        };
        RouteWeatherDto: {
            route: components["schemas"]["LatLngDto"][];
        };
        RouteWeatherPointDto: {
            temperature_c: number;
            /** @enum {string} */
            condition: "clear" | "cloudy" | "rain" | "storm" | "snow" | "fog" | "ice";
            wind_kmh: number;
            precipitation_chance: number;
            /** @enum {string} */
            road_condition: "dry" | "wet" | "icy" | "unknown";
            /** @example 14°C · Dry roads · Wind 12 km/h */
            description: string;
            lat: number;
            lng: number;
        };
        RouteWeatherResponseDto: {
            points: components["schemas"]["RouteWeatherPointDto"][];
            has_alerts: boolean;
            alerts: string[];
        };
        CommuteRouteResponseDto: {
            id: string;
            name: string;
            origin: components["schemas"]["LatLngDto"];
            destination: components["schemas"]["LatLngDto"];
            distance_km: number | null;
            avg_quality: number | null;
            is_primary: boolean;
            created_at: string;
        };
        CreateCommuteRouteDto: {
            /** @default Default */
            name: string;
            origin: components["schemas"]["LatLngDto"];
            destination: components["schemas"]["LatLngDto"];
        };
        CommuteStatusResponseDto: {
            route: components["schemas"]["CommuteRouteResponseDto"];
            hazard_count: number;
            route_quality: number | null;
            /** @enum {string} */
            status: "clear" | "hazards" | "weather_warning" | "delays";
        };
        DailyBreakdownDto: {
            date: string;
            rides: number;
            km: number;
            duration_min: number;
        };
        CommuteStatsResponseDto: {
            period: string;
            total_rides: number;
            total_km: number;
            total_time_min: number;
            avg_duration_min: number;
            fuel_estimate_l: number;
            daily_breakdown: components["schemas"]["DailyBreakdownDto"][];
        };
        ReviewResponseDto: {
            id: string;
            user_display_name: string;
            rating: number;
            comment: string | null;
            bike_model: string | null;
            created_at: string;
        };
        CreateReviewDto: {
            rating: number;
            comment?: string;
            /** @example BMW R1250GS */
            bike_model?: string;
        };
        FollowUserResponseDto: {
            following_id: string;
            display_name: string;
            followed_at: string;
        };
        FollowerDto: {
            user_id: string;
            display_name: string;
            followed_at: string;
        };
        FollowingDto: {
            user_id: string;
            display_name: string;
            followed_at: string;
        };
        FeedRideDto: {
            ride_id: string;
            share_token: string;
            rider_id: string;
            rider_name: string;
            ride_type: string;
            started_at: string;
            distance_km: number | null;
            avg_speed: number | null;
            avg_road_quality: number | null;
            duration_min: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_listContacts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactResponseDto"][];
                };
            };
        };
    };
    UsersController_addContact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContactDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactResponseDto"];
                };
            };
        };
    };
    UsersController_deleteContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contactId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Contact not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HazardsController_findNearby: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                radius?: number;
                /** @description Comma-separated hazard types */
                types?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HazardResponseDto"][];
                };
            };
        };
    };
    HazardsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHazardDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HazardResponseDto"];
                };
            };
        };
    };
    HazardsController_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hazardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HazardResponseDto"];
                };
            };
            /** @description Hazard not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HazardsController_dismiss: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hazardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Hazard not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HazardsController_findAlongRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteHazardsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HazardResponseDto"][];
                };
            };
        };
    };
    SensorController_upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadSensorDataDto"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponseDto"];
                };
            };
        };
    };
    RoadsController_findNearby: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                radius?: number;
                min_quality?: number;
                surface_type?: "asphalt" | "concrete" | "cobblestone" | "gravel" | "dirt";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadSegmentDto"][];
                };
            };
        };
    };
    RoadsController_findFunZones: {
        parameters: {
            query: {
                /** @description Bounding box: west,south,east,north */
                bbox: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunZoneDto"][];
                };
            };
        };
    };
    RoadsController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                segmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadSegmentDetailDto"];
                };
            };
            /** @description Road segment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SharingController_toggleShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleShareDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharedRideResponseDto"];
                };
            };
            /** @description Ride not completed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ride not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SharingController_unshare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Shared ride not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SharingController_getSharedRide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharedRideDetailDto"];
                };
            };
            /** @description Shared ride not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SharingController_listCommunityRides: {
        parameters: {
            query: {
                /** @description Latitude of search center */
                lat: number;
                /** @description Longitude of search center */
                lng: number;
                /** @description Search radius in km */
                radius_km?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityRideDto"][];
                };
            };
        };
    };
    RidesController_list: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                type?: "free" | "commute" | "trip" | "tracked";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideListResponseDto"];
                };
            };
        };
    };
    RidesController_start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRideDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideResponseDto"];
                };
            };
            /** @description Already have an active ride */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RidesController_stop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideResponseDto"];
                };
            };
            /** @description Ride not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RidesController_getDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideDetailDto"];
                };
            };
            /** @description Ride not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RidesController_importGpx: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideSummaryDto"];
                };
            };
        };
    };
    RidesController_exportGpx: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GPX file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ride not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SafetyController_sendCrashAlert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrashAlertDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrashAlertResponseDto"];
                };
            };
        };
    };
    TilesController_getTile: {
        parameters: {
            query?: {
                layers?: "quality" | "surface" | "hazards" | "all";
            };
            header?: never;
            path: {
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mapbox Vector Tile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Empty tile (no data in area) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WeatherController_getCurrent: {
        parameters: {
            query: {
                lat: number;
                lng: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherResponseDto"];
                };
            };
        };
    };
    WeatherController_getRouteWeather: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteWeatherDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteWeatherResponseDto"];
                };
            };
        };
    };
    CommuteController_listRoutes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommuteRouteResponseDto"][];
                };
            };
        };
    };
    CommuteController_createRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommuteRouteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommuteRouteResponseDto"];
                };
            };
        };
    };
    CommuteController_deleteRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Route not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommuteController_getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommuteStatusResponseDto"];
                };
            };
            /** @description No primary commute route */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommuteController_getStats: {
        parameters: {
            query?: {
                period?: "week" | "month";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommuteStatsResponseDto"];
                };
            };
        };
    };
    ReviewsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                segmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponseDto"][];
                };
            };
        };
    };
    ReviewsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                segmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponseDto"];
                };
            };
            /** @description Review not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReviewsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                segmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponseDto"];
                };
            };
            /** @description Already reviewed this segment */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReviewsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                segmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Review not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FollowersController_follow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowUserResponseDto"];
                };
            };
            /** @description Cannot follow yourself */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Already following */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FollowersController_unfollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not following this user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FollowersController_listFollowers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowerDto"][];
                };
            };
        };
    };
    FollowersController_listFollowing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowingDto"][];
                };
            };
        };
    };
    FollowersController_getFeed: {
        parameters: {
            query?: {
                /** @description Latitude to filter rides by location */
                lat?: number;
                /** @description Longitude to filter rides by location */
                lng?: number;
                /** @description Search radius in km (requires lat/lng) */
                radius_km?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedRideDto"][];
                };
            };
        };
    };
}
