import { auth } from "@/lib/auth";
import { NextResponse } from "next/server";
import {
  DEFAULT_LOCALE,
  LOCALE_COOKIE,
  PUBLIC_LOCALE_HEADER,
  PUBLIC_LOCALE_QUERY_PARAM,
  isSupportedLocale,
} from "@/i18n";
import {
  buildContentSecurityPolicy,
  createNonce,
} from "@/lib/security-headers";

// Paths accessible without authentication. Public marketing / SEO pages
// (road quality explorer, etc.) live here so search engines and visitors
// can reach them without the login wall.
const PUBLIC_PATHS = [
  "/explore",
  "/roads/best",
  "/rides/shared",
  "/rides/road-map/shared",
  "/trips/shared",
  "/community/collections/shared",
];
const LOCALIZED_PUBLIC_PATHS = ["/explore", "/roads/best"];

const PROTECTED_PATHS = [
  "/",
  "/trips",
  "/rides",
  "/community",
  "/achievements",
  "/settings",
];

export const middleware = auth((req) => {
  const { nextUrl, auth: session } = req;
  const isAuthenticated = !!session?.user;
  const isAuthPage =
    nextUrl.pathname.startsWith("/login") ||
    nextUrl.pathname.startsWith("/register") ||
    nextUrl.pathname.startsWith("/forgot-password");
  const isApiRoute = nextUrl.pathname.startsWith("/api");
  const isPublicPage = PUBLIC_PATHS.some(
    (path) =>
      nextUrl.pathname === path || nextUrl.pathname.startsWith(`${path}/`),
  );
  const isLocalizedPublicPage = LOCALIZED_PUBLIC_PATHS.some(
    (path) =>
      nextUrl.pathname === path || nextUrl.pathname.startsWith(`${path}/`),
  );
  const isProtectedPage = PROTECTED_PATHS.some((path) =>
    path === "/"
      ? nextUrl.pathname === "/"
      : nextUrl.pathname === path || nextUrl.pathname.startsWith(`${path}/`),
  );

  if (isApiRoute) return;

  if (isAuthPage && isAuthenticated) {
    return Response.redirect(new URL("/", nextUrl));
  }

  if (!isAuthPage && !isPublicPage && isProtectedPage && !isAuthenticated) {
    const loginUrl = new URL("/login", nextUrl);
    loginUrl.searchParams.set("callbackUrl", nextUrl.pathname);
    return Response.redirect(loginUrl);
  }

  // Per-request nonce CSP on every page response (redirects excluded — a 3xx
  // renders nothing). The policy is ALSO set on the forwarded REQUEST
  // headers: that is how Next discovers the nonce and stamps it onto its own
  // framework inline scripts, so `script-src 'nonce-…' 'strict-dynamic'` can
  // hold without an 'unsafe-inline' escape hatch.
  const nonce = createNonce();
  const csp = buildContentSecurityPolicy(nonce);
  const requestHeaders = new Headers(req.headers);
  requestHeaders.set("x-nonce", nonce);
  requestHeaders.set("Content-Security-Policy", csp);
  const withSecurity = (response: NextResponse) => {
    response.headers.set("Content-Security-Policy", csp);
    return response;
  };

  const requestedPublicLocale = nextUrl.searchParams.get(
    PUBLIC_LOCALE_QUERY_PARAM,
  );
  const publicLocale = requestedPublicLocale ?? DEFAULT_LOCALE;
  if (isLocalizedPublicPage) {
    if (!isSupportedLocale(publicLocale)) {
      return withSecurity(
        NextResponse.next({ request: { headers: requestHeaders } }),
      );
    }
    requestHeaders.set(PUBLIC_LOCALE_HEADER, publicLocale);
    const response = NextResponse.next({
      request: { headers: requestHeaders },
    });
    if (requestedPublicLocale) {
      response.cookies.set(LOCALE_COOKIE, publicLocale, {
        httpOnly: false,
        sameSite: "lax",
        path: "/",
      });
    }
    return withSecurity(response);
  }

  return withSecurity(
    NextResponse.next({ request: { headers: requestHeaders } }),
  );
});

// `runtime` pins this to Edge — Next 16 renamed this file convention to
// `proxy.ts` and defaults the renamed file to the Node runtime, which
// @opennextjs/cloudflare cannot yet bundle into a Worker (see
// opennextjs/opennextjs-cloudflare#1213). Keeping the legacy
// `middleware.ts` filename + `experimental-edge` is the upstream-blessed
// workaround until OpenNext ships Node-middleware support via its
// adapters API.
//
// The matcher excludes robots.txt and sitemap.xml (generated by
// `app/robots.ts` and `app/sitemap.ts`) so crawlers reach them without
// auth redirects.
export const config = {
  matcher: [
    "/((?!_next/static|_next/image|favicon.ico|robots.txt|sitemap.xml|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)",
  ],
  runtime: "experimental-edge",
};
