import React from "react";
import type { LucideIcon, LucideProps } from "lucide-react-native";
import {
  Activity,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bed,
  BellRing,
  Bike,
  Binoculars,
  BrickWall,
  Building2,
  Calendar,
  CalendarClock,
  CalendarRange,
  CalendarX,
  Camera,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleDot,
  CirclePause,
  CirclePlay,
  CirclePlus,
  CircleStop,
  Clock,
  ClockAlert,
  Cloud,
  CloudAlert,
  CloudCheck,
  CloudDownload,
  CloudFog,
  CloudLightning,
  CloudOff,
  CloudRain,
  CloudSnow,
  CloudUpload,
  Coffee,
  Construction,
  CornerLeftUp,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  Download,
  Droplet,
  Droplets,
  ExternalLink,
  EyeOff,
  FileUp,
  Flag,
  Flame,
  Folder,
  Fuel,
  Gauge,
  Grip,
  Hash,
  House,
  Image,
  Images,
  Info,
  LayoutGrid,
  LocateFixed,
  Lock,
  LogIn,
  LogOut,
  Map,
  MapPin,
  MapPinOff,
  MapPinPlus,
  MapPinned,
  MessageSquare,
  Minus,
  Mountain,
  Navigation,
  OctagonAlert,
  Pause,
  PawPrint,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Route,
  Send,
  Settings,
  Share2,
  ShieldAlert,
  ShieldCheck,
  Shovel,
  Smartphone,
  Snowflake,
  Star,
  Sun,
  Table,
  Target,
  Tent,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TriangleAlert,
  Trophy,
  User,
  UserCheck,
  UserPen,
  UserPlus,
  Users,
  Utensils,
  Volume2,
  VolumeX,
  WandSparkles,
  Waypoints,
  WifiOff,
  Wind,
  X,
} from "lucide-react-native";

/**
 * Tarmoto mobile icon set.
 *
 * A single wrapper over `lucide-react-native` so every glyph in the app comes
 * from one library — the same Lucide set the companion web app uses via
 * `lucide-react` — instead of the old `@react-native-vector-icons` Material
 * set. Call sites keep the familiar
 * `<Icon name="chevron-right" size={20} color={c} />` shape; `REGISTRY` maps
 * our stable kebab-case names (carried over from the previous Material names so
 * the migration was import-only) to Lucide components.
 *
 * Add an icon by adding a `"kebab-name": LucideComponent` entry plus its
 * import. `IconName` is derived from the registry keys, so any unknown name is
 * a compile error rather than a blank glyph at runtime.
 */
const REGISTRY = {
  account: User,
  "account-check-outline": UserCheck,
  "account-edit-outline": UserPen,
  "account-group": Users,
  "account-group-outline": Users,
  "account-multiple": Users,
  "account-multiple-outline": Users,
  "account-multiple-plus": UserPlus,
  "account-plus-outline": UserPlus,
  alert: TriangleAlert,
  "alert-circle": CircleAlert,
  "alert-circle-outline": CircleAlert,
  "alert-octagon": OctagonAlert,
  "alert-outline": TriangleAlert,
  "arrow-down": ArrowDown,
  "arrow-down-bold": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-left-top": CornerLeftUp,
  "arrow-right": ArrowRight,
  "arrow-right-top": CornerRightUp,
  "arrow-top-left": CornerUpLeft,
  "arrow-top-right": CornerUpRight,
  "arrow-up": ArrowUp,
  "arrow-up-bold": ArrowUp,
  "auto-fix": WandSparkles,
  "backup-restore": RotateCcw,
  bed: Bed,
  "bed-outline": Bed,
  "bell-ring-outline": BellRing,
  binoculars: Binoculars,
  "calendar-blank-outline": Calendar,
  "calendar-clock": CalendarClock,
  "calendar-range": CalendarRange,
  "calendar-remove-outline": CalendarX,
  camera: Camera,
  "camera-outline": Camera,
  "cellphone-link": Smartphone,
  check: Check,
  "check-circle": CircleCheck,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  circle: Circle,
  "circle-off-outline": CircleDashed,
  clock: Clock,
  "clock-alert": ClockAlert,
  "clock-outline": Clock,
  close: X,
  "cloud-alert-outline": CloudAlert,
  "cloud-check-outline": CloudCheck,
  "cloud-download-outline": CloudDownload,
  "cloud-off-outline": CloudOff,
  "cloud-upload-outline": CloudUpload,
  coffee: Coffee,
  "cog-outline": Settings,
  "comment-edit-outline": MessageSquare,
  counter: Hash,
  "crosshairs-gps": LocateFixed,
  domain: Building2,
  "dots-grid": Grip,
  "download-outline": Download,
  "exit-to-app": LogOut,
  "export-variant": Share2,
  "eye-off-outline": EyeOff,
  "file-upload-outline": FileUp,
  fire: Flame,
  "flag-checkered": Flag,
  "flag-outline": Flag,
  "folder-outline": Folder,
  "gas-station": Fuel,
  "gas-station-off": Fuel,
  gauge: Gauge,
  grain: Grip,
  "hammer-wrench": Construction,
  home: House,
  "home-outline": House,
  "home-roof": House,
  image: Image,
  "image-check": CircleCheck,
  "image-multiple": Images,
  "information-outline": Info,
  "lock-outline": Lock,
  "login-variant": LogIn,
  logout: LogOut,
  map: Map,
  "map-marker": MapPin,
  "map-marker-off-outline": MapPinOff,
  "map-marker-outline": MapPin,
  "map-marker-path": Waypoints,
  "map-marker-plus-outline": MapPinPlus,
  "map-marker-radius-outline": MapPinned,
  "map-outline": Map,
  "map-search-outline": Map,
  minus: Minus,
  motorbike: Bike,
  "navigation-variant": Navigation,
  "open-in-new": ExternalLink,
  pause: Pause,
  "pause-circle-outline": CirclePause,
  paw: PawPrint,
  "pencil-outline": Pencil,
  play: Play,
  "play-circle": CirclePlay,
  plus: Plus,
  "plus-circle": CirclePlus,
  "record-circle-outline": CircleDot,
  refresh: RefreshCw,
  reload: RotateCw,
  road: Route,
  "road-variant": Route,
  send: Send,
  "share-variant": Share2,
  "shield-alert": ShieldAlert,
  "shield-alert-outline": ShieldAlert,
  "shield-check": ShieldCheck,
  "shield-check-outline": ShieldCheck,
  shovel: Shovel,
  "silverware-fork-knife": Utensils,
  "sine-wave": Activity,
  snowflake: Snowflake,
  "snowflake-alert": Snowflake,
  speedometer: Gauge,
  "speedometer-medium": Gauge,
  star: Star,
  "star-outline": Star,
  "stop-circle": CircleStop,
  "stop-circle-outline": CircleStop,
  table: Table,
  target: Target,
  tent: Tent,
  terrain: Mountain,
  "thumb-down": ThumbsDown,
  "thumb-down-outline": ThumbsDown,
  "thumb-up": ThumbsUp,
  "thumb-up-outline": ThumbsUp,
  "trash-can-outline": Trash2,
  trophy: Trophy,
  "trophy-outline": Trophy,
  "view-grid": LayoutGrid,
  "view-grid-outline": LayoutGrid,
  "volume-high": Volume2,
  "volume-off": VolumeX,
  wall: BrickWall,
  "water-alert": Droplet,
  waves: Droplets,
  "weather-cloudy": Cloud,
  "weather-cloudy-alert": CloudAlert,
  "weather-fog": CloudFog,
  "weather-lightning-rainy": CloudLightning,
  "weather-rainy": CloudRain,
  "weather-snowy": CloudSnow,
  "weather-sunny": Sun,
  "weather-windy": Wind,
  "wifi-off": WifiOff,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof REGISTRY;

/**
 * Same call shape as the old Material `Icon` (name/size/color) plus every other
 * prop Lucide accepts — `style`, `strokeWidth`, and the react-native-svg /
 * accessibility pass-throughs (`accessibilityElementsHidden`, etc.) — so the
 * migration stayed import-only at the call sites.
 */
export type IconProps = { name: IconName } & Omit<LucideProps, "name">;

export function Icon({
  name,
  size = 24,
  ...rest
}: IconProps): React.ReactElement {
  const Glyph = REGISTRY[name];
  return <Glyph size={size} {...rest} />;
}
